name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc520b782b56ceaa36d147279c4d62960cda3cb1e7ff0cd5088eee7652a9fee1"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
