name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58c0dcb1b490073ba065be4801e1833a276bc997a962fad591e26c6aeb192233"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
