name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7c059a7c049a6d1c9eac6baa9bba24ccdca95eabc0175a380596134af25c201"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
