name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed398ccdd42491554e5383c8df68a28c1438bb6a7fa728dc08b8fa4effd3cdf1"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
