name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92e803bfdf587d1038b75c401421fed62674432eb5792b4f02ce6f1d92479dba"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
