name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69c4fa5a2b2e5f5cb1d2cfcb7b0669f77a82fef592678096cb52be8b524c0e82"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
