name = "Hex Creator"
author = "Teal Wolf 25"
version = "4.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e330f1f83e2a9ae25d3975a0d478f42d17e3e9c390bcb51a7f67c84f1593dfcb"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
